name: taska
description: Manage tasks efficiently.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  app_settings: ^5.1.1
  device_info_plus: ^10.1.0
  device_preview: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_local_notifications: ^17.1.2
  flutter_native_splash: ^2.4.0
  flutter_slidable: ^3.1.0
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  sliver_tools: ^0.2.12
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  table_calendar: ^3.0.9
  timezone: ^0.9.3
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter_native_splash:
  image: assets/images/splash.png
  color: "#113826"
  fullscreen: true
  android_12:
    image: assets/images/splash_12.png
    color: "#113826"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-Medium.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
    - family: Constantia
      fonts:
        - asset: fonts/Constantia-Bold.ttf
        - asset: fonts/Constantia-Regular.ttf
